# Generated by Django 5.2.15 on 2026-08-19 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_system', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ['-date_joined'], 'verbose_name': 'Користувач', 'verbose_name_plural': 'Користувачі'},
        ),
    ]
