# Generated by Django 5.2.15 on 2026-06-15 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=30, verbose_name='Прізвище')),
                ('first_name', models.CharField(max_length=30, verbose_name='Імʼя')),
                ('phone_number', models.CharField(max_length=15, unique=True, verbose_name='Номер телефону')),
                ('tg', models.CharField(blank=True, max_length=32, null=True, unique=True, verbose_name='Нікнейм в телеграм')),
                ('gender', models.CharField(choices=[('-', '-'), ('male', 'Чоловік'), ('female', 'жінка')], max_length=10)),
                ('birthdate', models.DateField(blank=True, null=True, verbose_name='Дата народження')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Клієнт',
                'verbose_name_plural': 'Клієнти',
                'ordering': ('-created_at',),
            },
        ),
    ]
