# Generated by Django 5.2.15 on 2026-06-16 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientmodel',
            name='gender',
            field=models.CharField(choices=[('-', '-'), ('male', 'Чоловік'), ('female', 'Жінка')], default='-', max_length=10),
        ),
    ]
