# Generated by Django 5.2.15 on 2026-07-05 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MasterModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=30, verbose_name='Прізвище')),
                ('first_name', models.CharField(max_length=30, verbose_name='Імʼя')),
                ('phone_number', models.CharField(max_length=15, unique=True, verbose_name='Номер телефону')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Майстер',
                'verbose_name_plural': 'Майстри',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ProcedureModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Назва')),
                ('description', models.TextField(verbose_name='Опис')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ціна')),
                ('duration', models.PositiveIntegerField(verbose_name='Тривалість')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Процедура',
                'verbose_name_plural': 'Процедури',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='MasterScheduleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('start_time', models.TimeField(verbose_name='Час початку роботи')),
                ('end_time', models.TimeField(verbose_name='Час завершення роботи')),
                ('is_day_off', models.BooleanField(default=False, verbose_name='Вихідний')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='procedures.mastermodel')),
            ],
            options={
                'verbose_name': 'Розклад майстра',
                'verbose_name_plural': 'Розклад майстрів',
                'ordering': ('-date',),
            },
        ),
        migrations.CreateModel(
            name='MasterProcedureModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='master_procedures', to='procedures.mastermodel')),
                ('procedure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procedure_masters', to='procedures.proceduremodel')),
            ],
            options={
                'verbose_name': 'МайстерПроцедура',
                'unique_together': {('master', 'procedure')},
            },
        ),
    ]
