# Generated by Django 5.2.15 on 2026-07-06 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedures', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mastermodel',
            name='color',
            field=models.CharField(default='#0d6efd', max_length=7, verbose_name='Колір в календарі'),
        ),
    ]
