# Generated by Django 5.2.15 on 2026-06-20 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedures', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterproceduremodel',
            name='procedure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procedures', to='procedures.proceduremodel'),
        ),
    ]
