# Generated by Django 5.2.15 on 2026-07-07 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedures', '0002_mastermodel_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proceduremodel',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Опис'),
        ),
    ]
