# Generated by Django 5.2.10 on 2026-06-21 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedures', '0002_alter_masterproceduremodel_procedure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proceduremodel',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Назва'),
        ),
    ]
