# Generated by Django 5.2.15 on 2026-06-22 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedures', '0003_alter_proceduremodel_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterproceduremodel',
            name='master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='master_procedures', to='procedures.mastermodel'),
        ),
        migrations.AlterField(
            model_name='masterproceduremodel',
            name='procedure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procedure_masters', to='procedures.proceduremodel'),
        ),
    ]
