# Generated by Django 5.2.15 on 2026-08-19 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedures', '0003_alter_proceduremodel_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proceduremodel',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Вартість'),
        ),
    ]
