# Generated by Django 5.2.15 on 2026-07-05 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('procedures', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_at', models.DateTimeField(verbose_name='Початок')),
                ('end_at', models.DateTimeField(blank=True, null=True, verbose_name='Завершення')),
                ('status', models.CharField(choices=[('booked', 'Заброньовано'), ('done', 'Виконано'), ('canceled', 'Відмінено'), ('no_show', 'Приховано')], default='booked', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.clientmodel', verbose_name='Клієнт')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='procedures.mastermodel', verbose_name='Майстер')),
                ('procedure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='procedures.proceduremodel', verbose_name='Процедура')),
            ],
            options={
                'verbose_name': 'Запис клієнта',
                'verbose_name_plural': 'Записи клієнтів',
                'ordering': ('-start_at',),
            },
        ),
    ]
