# Generated by Django 5.2.15 on 2026-07-06 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentmodel',
            name='comment',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Примітка'),
        ),
    ]
