# Generated by Django 5.2.15 on 2026-07-07 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_appointmentmodel_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentmodel',
            name='comment',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Коментар'),
        ),
        migrations.AlterField(
            model_name='appointmentmodel',
            name='status',
            field=models.CharField(choices=[('booked', 'Записано'), ('done', 'Виконано'), ('canceled', 'Відмінено')], default='booked', max_length=20, verbose_name='Статус'),
        ),
    ]
