# Generated by Django 5.2.15 on 2026-07-07 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_alter_appointmentmodel_comment_and_more'),
        ('procedures', '0003_alter_proceduremodel_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentmodel',
            name='procedure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='procedures.proceduremodel', verbose_name='Послуга'),
        ),
    ]
