# Generated by Django 5.2.15 on 2026-07-31 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_alter_appointmentmodel_procedure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentmodel',
            name='status',
            field=models.CharField(choices=[('booked', 'Записано'), ('done', 'Виконано'), ('canceled', 'Скасовано')], default='booked', max_length=20, verbose_name='Статус'),
        ),
    ]
