# Generated by Django 5.2.15 on 2026-08-20 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0005_alter_appointmentmodel_status'),
        ('procedures', '0004_alter_proceduremodel_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentmodel',
            name='master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='procedures.mastermodel', verbose_name='Майстер'),
        ),
    ]
